language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - cp .env.default .env
  - docker-compose build
  - docker-compose run service python -m unittest -v

after_success:
  - docker-compose run service codecov
